Kong/lua-resty-dns-client

README.md, spec/utils_spec.lua, src/resty/dns/utils.lua
implements the MAXNS setting to parse only the max number of nameservers
from resolv.conf instead of all of them
=> fix(resolv): implements MAXNS

README.md, spec/client_spec.lua, spec/utils_spec.lua, src/resty/dns/balancer.lua, src/resty/dns/client.lua, src/resty/dns/utils.lua
Also deprecates the `stdError` function. Generates an extra return
value for toip() and resolve() to track history of searches.
fixes #6
=> feat(client) implements `search` and `ndots` options

src/resty/dns/client.lua
add extensive logging on querying
=> do not lookup IP addresses if the type of query is not IPv4 or IPV6

README.md, spec/client_spec.lua, src/resty/dns/client.lua
was only caught if the query type was A or AAAA, now it will fail right away for any other type.
=> no longer lookup ip addresses on the dns server

README.md, spec/balancer_spec.lua, spec/client_cache_spec.lua, spec/client_spec.lua, src/resty/dns/balancer.lua, src/resty/dns/client.lua
lookups will be done in the background whenever possible.
This is a breaking change due to function signatures changing
=> Async lookups

spec/balancer_spec.lua, src/resty/dns/balancer.lua
Named entries in an SRV record would not return the hostname
properly, but always 'nil'.
See issue #17
=> fix(balancer) named SRV entries return hostname properly

spec/client_spec.lua, src/resty/dns/client.lua
This PR for now fixes the case for the `toip` function. But the ring-balancer should also be adjusted for this case.
=> Fix/zero weight SRV entries

README.md, spec/balancer_spec.lua, src/resty/dns/balancer.lua
Addresses #26 in branch 0.4.x, including a backport of test from PR #27.
=> [0.4.x] fix(balancer) when dns resolution fails for the last host

README.md, spec/client_spec.lua, src/resty/dns/client.lua
In a scenario with all lookups being ip based, the lack of nameservers should not fail.
fixes https://github.com/Kong/kong/issues/3104
=> fix(client) do not fail initialization without nameservers

README.md, spec/balancer_spec.lua, src/resty/dns/balancer.lua
In addition to #32 this adds more improvements, mostly on memory consumption.
Test case with a very large balancer having 100 targets and a size of 65535:
**Release 1.0**:
- Memory: 10.5 mb
- creation time: 95/100ms
**After #32 & #33**
- Memory: 1.7mb
- creation time: 10ms
Unfortunately it is a breaking change since the `host:getPeer()` method changed signature.
=> Reducing the memory footprint of large balancers

README.md, spec/client_spec.lua, spec/utils_spec.lua, src/resty/dns/client.lua, src/resty/dns/utils.lua
Additionally relaxes parsing to also allow for port numbers (in
custom hosts files). The DNS client will insert those entries
as SRV records in its cache (other entries will be A or AAAA
type records)
=> fix(hosts) ensure hostsfile ipv6 are also normalized with brackets

README.md, spec/client_cache_spec.lua, src/resty/dns/client.lua
If the additional section would contain a TXT record, then that would
be set as the success type, and `last` would try and look for that.
The cache lookup would succeed, but since it doesn't have a `address`
field, `toip()` would return `nil`.
fixes https://github.com/Kong/kong/issues/3210
=> fix(cache) do not set success types for records we're not resolving

README.md, spec/client_cache_spec.lua, src/resty/dns/client.lua
This can occur when a nameserver is configured to NOT reply to CNAME
queries. The empty result might overwrite the proper record that
was delivered along side an A query. This can only happen when
the data is stale, as only then individual refresh queries are send.
=> fix(client) prevent overwriting CNAME data in the cache

README.md, extra/analyze.lua, spec/client_cache_spec.lua, src/resty/dns/client.lua
records from the additional section would not be stored in the
cache when there already was a cache entry. This also means that
stale data was not replaced. The bug surfaced when a dns server
would not respond to CNAME queries, but only provide that data
alongside an A query.
To track the bug extensive logging was added (to be enabled manually),
and a script to re-format those logs.
=>  Fixes a bug for replacing stale data in the cache

README.md, spec/client_spec.lua, src/resty/dns/client.lua
Provide a nice log message and skip, instead of erroring out
fixes #43
=> fix(client) do not accept ipv6 resolvers with a scope

README.md, spec/client_spec.lua, src/resty/dns/client.lua
Implements a new option `validTtl` that, if given, overrides the
ttl of any valid answer received from the name server.
closes #48
=> feat(client) add option to override ttl

README.md, src/resty/dns/client.lua
New-line characters in the logging are impossible to parse
correctly so should be prevented.
fixes #52
=> fix(logging) encode try-list as json and no longer use new-line

README.md, spec/client_spec.lua, src/resty/dns/client.lua
Treat the localhost name special by always injecting it, according
to RFC 6761: Section 6.3.3
fixes #50
=> fix(client) always inject localhost

README.md, src/resty/dns/balancer.lua
See https://github.com/Kong/lua-resty-dns-client/issues/51
Some servers will report ttl=0 when they are on the very edge
of their own cached ttl. This should never happen for a record
that has a non-0 ttl.
This fix makes sure we require ttl=0 reported twice in a row before
we switch the loadbalancer.
Fixes #51
=> fix(balancer) fix accidental ttl=0 switches

lua-resty-dns-client-2.2.0-1.rockspec, spec/balancer_base_spec.lua, spec/balancer_spec.lua, spec/client_cache_spec.lua, spec/client_spec.lua, spec/test_helpers.lua, spec/utils_spec.lua, src/resty/dns/balancer.lua, src/resty/dns/balancer_base.lua
A lot of the code in the balancer is DNS related, fanning out hosts
to underlying addresses and tracking them over DNS updates.
This disentangles them, such that the DNS related code now becomes
a base class that can be used to build balancers on top. The ring
balancer just being one of them.
Todo:
=> refactor(balancer) split dns and balancer logic

spec/balancer_base_spec.lua, spec/balancer_spec.lua, spec/handle_spec.lua, src/resty/dns/balancer.lua, src/resty/dns/balancer_base.lua, src/resty/dns/handle.lua
Setting status wasn't always possible, if an address still contained a name instead of an ip (SRV -> A -> ip).
By returning a handle, the proper reference is preserved, and as a side effect the `retryCount` parameter is now obsolete.
Signature of `getPeer` changed, and hence this is a breaking change
NOTE: this is not against `master`, but `split-balancer` to avoid too many conflicts
=> fix(balancer) introduce a handle to set peer status

README.md, spec/balancer/ring_spec.lua, src/resty/dns/balancer/base.lua
Fix for issue #49 
The problem was introduced by the addition of callbacks for Kong healthchecks. Before the entire update of the balancer was atomic. But the healthchecks do an implicit yield, and hence multiple updates started to run simultaneously.
The solution now is (since the callbacks are beyond the control of the balancer lib) to use an explicit lock/semaphore to force atomicity, or to execute the callbacks delayed.
Since we cannot use a lock/semaphore in the balancer phase, it has to be delayed.
=> fix(balancer) make wheel updates atomic

README.md, src/resty/dns/client.lua
The error was returned, but not all callers would properly check
the results. Hence log it where it happens.
=> fix(client) log failure to create a timer

README.md, spec/balancer/base_spec.lua, spec/balancer/generic_spec.lua, spec/balancer/least_connections_spec.lua, spec/balancer/ring_spec.lua, spec/client_cache_spec.lua, spec/client_spec.lua, src/resty/dns/balancer/base.lua, src/resty/dns/balancer/least_connections.lua, src/resty/dns/balancer/ring.lua, src/resty/dns/client.lua
Since the health was introduced on the balancer, there is an early
exit if the balancer is unhealthy. This introduced a problem where
DNS record would remain untouched, and hence would not be refreshed.
Leaving the balancer in an unhealthy state forever.
issue: https://github.com/Kong/kong/issues/4781
=> fix(balancer) recover after dns updates

README.md, src/resty/dns/balancer/base.lua
instead of logging each start and end (every second), now only
log when a host is actually being requeried.
=> fix(logging) reduce noise of the requery timer

src/resty/dns/balancer/base.lua
I cannot reproduce this easily, but I've had a crash in the logs
caused by attempting to dereference `self.lastQuery.expire` when
`self.lastQuery` was `nil`.
Patched it like this to match the coding style present in this
module.
=> fix(base) avoid a crash when self.lastQuery is not set

src/resty/dns/balancer/base.lua
This commit is try to fix :[#80](https://github.com/Kong/lua-resty-dns-client/issues/80) issue
=> attempt to index field  host.lastQuery a nil value

README.md, src/resty/dns/balancer/base.lua, src/resty/dns/balancer/handle.lua, src/resty/dns/balancer/least_connections.lua, src/resty/dns/balancer/ring.lua, src/resty/dns/client.lua
* the previous record was not properly detected as a ttl=0 record
by checking on the __ttl0flag we now do
* since the "fake" SRV record wasn't updated with a new expiry
time the expiry-check-timer would keep updating that record
every second
Fixes Kong issue https://github.com/Kong/kong/issues/5477
=> fix(balancer) fix ttl-0 records issues

README.md, spec/balancer/generic_spec.lua, src/resty/dns/balancer/base.lua
Status report now has an additional field `dns` on the reported `host` level. This field can have multiple values;
- record type the DNS resolved to; eg. `A`, `AAAA`, `SRV`. Hosts added as IP addresses will show up here as their respective types; ipv4 as `A`, ipv6 as `AAAA`
- for records with `ttl=0` the value will be `ttl=0, virtual SRV`
- for DNS errors it will report the error; eg. `dns server error: 3 name error`
=> feat(status) report dns source data on status

README.md, src/resty/dns/balancer/base.lua
The balancer was calling `toip` on the dns-client module, instead
of using the dns client passed to it.
Since the module is to be used as a singleton anyway, this did not
affect any real usage. But in testing the cache would not be
properly reset, since there we reload the entire module forcefully.
=> fix(balancer) use proper dns client

README.md, spec/balancer/base_spec.lua, spec/balancer/generic_spec.lua, src/resty/dns/balancer/base.lua
This enables the balancer to return a host-header.
So far the returned "host" was always the name of the host as it was added to the balancer by calling `addHost()`. With this PR there is a change between the Host as added and the host-header to be used on a request.
- `getPeer()` will return the host-header instead of the name. The **_breaking change_** here is that if the name as added is an IP address, then the host-header returned will be `nil`. Otherwise, with all defaults everything will be the same.
- the balancer gets a new option `useSRVname` (`false` by default), which if set, will instruct the returned Host-header to be the name inside an SRV record. If not and SRV record, then it will return the hostname as added to the balancer (as before).
- the callback for adding/removing …
=> feat(balancer) option to return nested SRV name as hostname

lua-resty-dns-client-5.0.1-1.rockspec, spec/balancer/consistent_hashing_spec.lua, src/resty/dns/balancer/consistent_hashing.lua
A new consistent hashing algorithm was added. It should not rely on the order of adding and removing addresses to always build the same balancing strategy.
=> feat(balancer) new consistent hashing algorithm

spec/utils_spec.lua, src/resty/dns/utils.lua
Currently, domains ending with a number (can happen in internal networks) are parsed wrongly - the trailing number is assumed to be a port. The issue only affects "name" hostname types. 
Examples:
```
test-host123 -> host: test-host, port: 123
test-host.local.domain123 -> host: test-host.local.domain, port: 123
```
The PR change reuses the "ipv4" regex for the "name" type, as it's valid for both cases.
=> fix hostname and port parsing

spec/balancer/generic_spec.lua, src/resty/dns/balancer/base.lua
This implementation of timer reduction uses a binary heap to sort the values up for renewal, so the update mechanism does not iterate over all targets in all balancers, but only checks the ones to renew. So this is more efficient.
=> fix(timers) reduce timers used

README.md, spec/balancer/consistent_hashing_spec.lua, spec/balancer/ring_spec.lua, src/resty/dns/balancer/base.lua
Busy-loop created when renewing expired dns records
=> fix(base) fix issue with 100% CPU

src/resty/dns/balancer/ring.lua
s/relinguish/relinquish
Signed-off-by: Joshua Schmid <jxs@posteo.de>
=> docs(lua-resty-dns-client) fix typo

README.md, src/resty/dns/balancer/least_connections.lua
remove address from binary heap upon 'disabling' instead of when
'deleting'. Seems safer to prevent race conditions. This means that in between disabling and deleting the address can no longer be selected by GetPeer.
=> fix(least-conn) change cleanup order

src/resty/dns/client.lua
relies on PR https://github.com/openresty/lua-resty-dns/pull/55, added the not-merge label until that PR is approved and merged.
NOTE: this changes default behaviour from openresty defaults (`no_random = false`), to proper dns defaults (`rotate = false` --> `no_random = true`). It will not break anything, but will distribute load differently.
=> feat(client) honor resolv.conf option rotate

spec/balancer/generic_spec.lua, spec/test_helpers.lua
@locao we missed these tests when adding the new consistent-hashing implementation. Can you have a look at the failures?
=> fix(tests) enable generic tests on consistent-hashing balancer

.gitignore, .travis.yml, README.md, src/resty/dns/client.lua, t/00-sanity.t, t/001-init.t, t/01-phases.t, t/02-timer-usage.t
We end up scheduling 1 timer for each hostname on the init_worker phase. To fix it we are "deduplicating" timers created to resolve the same hostname for the asynchronous case. That is, we are reusing timers for DNS queries of the same hostname. If we have 6k targets, and all of the targets are "httpbin.org" there's no reason to create 6k timers per worker. Instead, we should just create a maximum of 3 timers for 3 DNS queries (default: 1 for SRV, 1 for A and 1 for CNAME) and don't schedule more timers than that to resolve the same hostname. We should only schedule more timers if we try to resolve different hostnames. And the approach we're using in the patch is: if the current nginx phase can't be blocked by a semaphore (which is the case of init_worker context, but not of timer …
=> perf(client) reduce amount of timers on init_worker

README.md, spec/client_cache_spec.lua, src/resty/dns/client.lua
entries from hosts files
See: https://github.com/Kong/kong/issues/7444 for bug report
The `validTtl` setting forcibly overwrites TTL inside the `cacheinsert`
function. However, this inadvertently overrides the TTL of hosts file
entries as well so that they may expire prematurely, causing resolving
failures later.
This PR changes so that `validTtl` will only be enabled after all
entries from hosts file are inserted.
=> fix(client) ensure `validTtl` override does not interfere with TTL of

src/resty/dns/client.lua
`ssl_cert` and `ssl_session_fetch` can both yield, but were missing from
the supported list. Without this, a client running in one of these
phases may fail to resolve unexpectedly.
=> fix(client) allow semaphore wait in some ssl_* phases
